OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
# HAPTIC_DRIVER = DRV2605L
DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
TRI_LAYER_ENABLE = no
SPLIT_KEYBOARD = yes
SWAP_HANDS_ENABLE = no

HAPTIC_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no

RGB_MATRIX_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes